## TensorFlow unstack使用 

### unstack at axis = 0
![Alt text](./images/basic_tensorflow/unstack_axis0.png)
### unstack at axis = 1
![Alt text](./images/basic_tensorflow/unstack_axis1.png)
### unstack at axis = 2
![Alt text](./images/basic_tensorflow/unstack_axis2.png)


In [3]:
import tensorflow as tf
x = tf.constant([[0.7,0.9],[0.1,0.4],[0.5,0.8]], name='x')
print(x.shape)  # (3,2)
print('x=\n',x.numpy())
axis0_x = tf.unstack(x, axis=1)  # axis=0, 表示拆成3堆，每堆2個元素， axis=1, 表示拆2
print(axis0_x[0])
print(axis0_x[1])
# print(axis0_x[2])

(3, 2)
x=
 [[0.7 0.9]
 [0.1 0.4]
 [0.5 0.8]]
tf.Tensor([0.7 0.1 0.5], shape=(3,), dtype=float32)
tf.Tensor([0.9 0.4 0.8], shape=(3,), dtype=float32)


## TensorFlow stack使用

### origin data
![Alt text](./images/basic_tensorflow/stack_origin.png)
### stack at axis = 0
![Alt text](./images/basic_tensorflow/stack_axis0.png)
### stack at axis = 1
![Alt text](./images/basic_tensorflow/stack_axis1.png)

In [8]:
x = tf.constant([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]], name='x')
print('x=\n',x, x.shape)
y = tf.constant([[1.0, 1.0], [0.0, 1.0], [1.0, 1.0]], name='y')
print('y=\n',y, y.shape)
stacked_axis0_result = tf.stack([x,y], axis=0)
stacked_axis1_result = tf.stack([x,y], axis=1)
stacked_axis2_result = tf.stack([x,y], axis=2)

print('stacked_axis0_result=\n',stacked_axis0_result)
print(stacked_axis0_result.shape)
    
print('stacked_axis1_result=\n',stacked_axis1_result)
print(stacked_axis1_result.shape)

print('stacked_axis2_result=\n',stacked_axis2_result)
print(stacked_axis2_result.shape)

x=
 tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float32) (3, 2)
y=
 tf.Tensor(
[[1. 1.]
 [0. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32) (3, 2)
stacked_axis0_result=
 tf.Tensor(
[[[1. 2.]
  [3. 4.]
  [5. 6.]]

 [[1. 1.]
  [0. 1.]
  [1. 1.]]], shape=(2, 3, 2), dtype=float32)
(2, 3, 2)
stacked_axis1_result=
 tf.Tensor(
[[[1. 2.]
  [1. 1.]]

 [[3. 4.]
  [0. 1.]]

 [[5. 6.]
  [1. 1.]]], shape=(3, 2, 2), dtype=float32)
(3, 2, 2)
stacked_axis2_result=
 tf.Tensor(
[[[1. 1.]
  [2. 1.]]

 [[3. 0.]
  [4. 1.]]

 [[5. 1.]
  [6. 1.]]], shape=(3, 2, 2), dtype=float32)
(3, 2, 2)
